version: '2'

services:
    web:
        image: whw3/nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./log:/var/log/nginx
        networks:
            - code-network
    php:
        image: whw3/php:latest
        volumes:
            - ./code:/code
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini
            - ./conf/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
